# Banco local
spring.datasource.url=jdbc:postgresql://localhost:5432/seu_banco
spring.datasource.username=postgres
spring.datasource.password=postgres

# JWT local
api.security.token.secret=Nia1ncwoi2pn3niNo4inO42nbad

# Porta
server.port=8080