name: CI Backend

on:
  push:
    branches: [ "main", "backend" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v3

      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 📦 Build com Maven
        run: cd backend && mvn clean package -DskipTests

      - name: 🐳 Build da imagem Docker
        run: docker build -t backend-api ./backend

      - name: 🚀 Teste com H2
        run: |
          CONTAINER_ID=$(docker run -d -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb \
            -e SPRING_FLYWAY_ENABLED=false \
            -e API_SECURITY_TOKEN_SECRET=teste \
            backend-api)

          echo "Aguardando API subir..."
          sleep 30

          if curl -f http://localhost:8080; then
            echo "API OK"
          else
            echo "Falha na API"
            docker logs $CONTAINER_ID
            exit 1
          fi